### ISSUE TITLE
[tvOS] can't scroll to see all screen

### ISSUE THREAD

**Issue by MrADOY** [paololeonardi/WaterfallGrid#10]
Hello, 

I run it on simulator and I don't know if it's a bug but you can't scroll to see all screen on AppleTV, I think it's because images are not focusable..

<img width="1440" alt="Capture d’écran 2019-11-13 à 09 51 13" src="https://user-images.githubusercontent.com/26259051/68747694-5dfccc00-05fb-11ea-9aa2-eef90659ecaf.png">

**Comment by paololeonardi** [comment]
Hi @MrADOY, 
thanks for highlighting this.

Yes, it's happening because the views are not focusable.
I didn't give to this high priority because is just a demo app improvement. And in some ways to not overcomplicate the demo code.


But nice to have. Happy if you or other contributors want to pick this up, or I'll look into it myself on one of the next releases.

Thanks,
Paolo

**Comment by traceypooh** [comment]
If they're not focusable, they also can't be clicked, right?
In tvOS, I'm looking at an array of imagery, that's unscrollable, and unclickable.
That's _expected_ right now?

**Comment by traceypooh** [comment]
ooooooh!  answered my own question, taking a clue from QImage feedback...

If I wrap my `VStack { }` (image on top, title below) each of them with `Button() { ... }`

_then_ tvOS is scrollable and each "cell" is selectable.

I'll let you decide if I just made this ticket CLOSED, hehe :)

Thanks for this awesome software!  Very helpful for my app...
