### ISSUE TITLE
Self-adopting to different devices?

### ISSUE THREAD

**Issue by innoreq** [paololeonardi/WaterfallGrid#27]
I'm using the WaterfallGrid in my own application. Although it's a great help, it seems that it does not adopt itself to the device.

This is how I integrated it:

```
var body: some View {
		
		Frame(title: "My Personal Data") {
			
			ForEach(self.model.content.rows) { row in
				
				VStack {
					
					WaterfallGrid(row.cards) { card in
						
						SectionCard(content: card,
									configuration: card.configuration,
									onTapClosure: { id in
										
										debugPrint("Tapped: \(id)")
						})
					}
					.gridStyle(spacing: 50,
							   padding: EdgeInsets(top: 100, leading: 0, bottom: 0, trailing: 0))
				}
			}
		}
		.onAppear(perform: {
			
			self.model.load()
		})
	}
```

While on an iPad, everything looks fine:

![Simulator Screen Shot - iPad Air (3rd generation) - 2020-03-20 at 21 28 54](https://user-images.githubusercontent.com/43679379/77203982-0e229a00-6af2-11ea-8d00-4bb66b8fc7d1.png)

the iPhone display is not what I expected:

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-20 at 21 29 03](https://user-images.githubusercontent.com/43679379/77204107-53df6280-6af2-11ea-9632-aab6995b7861.png)

Am I doing something wrong?

**Comment by paololeonardi** [comment]
Hi @innoreq, thank you for using the grid!

I believe I see where the issue is:
The screenshots suggest that in your implementation of  `SectionCard` you are specifying a fixed size for the view’s width.

In doing so, you are forcing the elements to use their own width and ignore the size the grid wants for them.
Spacing 50 is being ignored in both devices. But in the iPhone, two cards don't fit the screen and overlap.

So if I'm right, the solution would just be to change `SectionCard` in a way that has no fixed width.

Hope this helps,
Thanks.
